### ISSUE TITLE
request to add: www.caixin.com

### ISSUE THREAD

**Issue by ForeverCan** [magnolia1234-new/bypass-paywalls-chrome-clean#10]
i see the default bypass lists including Caixin Global site with "caixinglobal.com"

so, is it possible to bypass the pay wall of the Caixin Chinese site "caixin.com"?

I tried to add it myself, but it doesn't work, thanks.

e.g.   http://finance.caixin.com/2020-04-24/101546858.html

**Comment by magnolia1234-new** [comment]
Caixin has a hard paywall (subscription-only).

**Comment by ForeverCan** [comment]
> Caixin has a hard paywall (subscription-only).

what's the difference between 'hard' paywall and soft? one

**Comment by magnolia1234-new** [comment]
To put it simply, the soft paywalls can be bypassed.
