### ISSUE TITLE
Mirrors

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234-new/bypass-paywalls-chrome-clean#2]
Do you think you might mirror your fork on Gitlab, Bitbucket and the download releases published on Sourceforge/OneDrive?

I'd be so devo if you have vanished again

**Comment by magnolia1234-new** [comment]
> Do you think you might mirror your fork on Gitlab, Bitbucket and the download releases published on Sourceforge/OneDrive?
> 
> I'd be so devo if you have vanished again

Sure, I've been thinking about that already.

**Comment by danielgruber8** [comment]
FYI my Aussie pal runs his own Carrotlabs Git repo
https://git.carrotlabs.net/explore/snippets
