### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234-new/bypass-paywalls-chrome-clean#3]
Links to "archive" folder
https://github.com/magnolia1234-new/bypass-paywalls-chrome-clean/archive/master.zip

**Comment by magnolia1234-new** [comment]
Relax, that's normal.

**Comment by danielgruber8** [comment]
can't blame me for getting excited as I thought you disappeared for good........don't you want to make the chrome and firefox versions the same since you started clean ?

**Comment by magnolia1234-new** [comment]
Sourcecode is like 99% equal already.
This leaves room for specific browser fixes.

**Comment by danielgruber8** [comment]
There is a > in "Financial" in the readme.md ;)

**Comment by magnolia1234-new** [comment]
Corona-boredom is kicking in already? ;-)
Btw > is intentional.
