### ISSUE TITLE
Could not load manifest on Yandex Android

### ISSUE THREAD

**Issue by ForeverCan** [magnolia1234-new/bypass-paywalls-chrome-clean#4]
I followed the instructions, but he Yandex from Google Play could not load the manifest.json file. It says 'Manifest file is missing or unreadble'.

**Comment by magnolia1234-new** [comment]
Did you folllow the Android-instruction and use the unpacked (master)zip-file instead of the crx-file?

**Comment by ForeverCan** [comment]
Yes , I downloaded the zip file and unzipped it.

**Comment by magnolia1234-new** [comment]
Should work just fine though (still sounds like the zip-file is not unpacked).
How did you unzip it?

**Comment by ForeverCan** [comment]
Solid Explorer, I'll try other ways.

**Comment by ForeverCan** [comment]
I unzipped it both with Samsung  'My Files' app and Solid Explorer app, neither works.

**Comment by magnolia1234-new** [comment]
Try selecting manifest.json with Total Commander.

**Comment by ForeverCan** [comment]
Great, thanks. I unzipped with TC, then it works.

**Comment by danielgruber8** [comment]
I am wondering which Android Yandex browser you are using? I think the alpha one works better...

**Comment by magnolia1234-new** [comment]
Just the stable version.
How does the experimental alpha/beta-version work better though?

**Comment by danielgruber8** [comment]
As per alpha description:

https://play.google.com/store/apps/details?id=com.yandex.browser.alpha
Use Chromium extension stores such as Chrome Web Store or Opera Addons to increase what you can do with Yandex Browser.

**Comment by magnolia1234-new** [comment]
Like beta/aurora releases of Chrome.
Stable version supports extension just fine.
