### ISSUE TITLE
Site request: Bild.de and Welt.de

### ISSUE THREAD

**Issue by TTVErraticAlcoholic** [magnolia1234-new/bypass-paywalls-chrome-clean#5]
Didn't seem to work even after adding them to the custom sites. Not sure what can be done about that.

https://www.bild.de/bild-plus/politik/inland/politik-inland/peter-altmaier-hohere-steuern-bringen-keine-hoheren-einnahmen-70124354,view=conversionToLogin.bild.html

https://www.welt.de/politik/deutschland/plus207328545/Sommerferien-2020-Warum-die-Chancen-fuer-Strandurlaub-in-Deutschland-steigen.html

**Comment by magnolia1234-new** [comment]
Both sites have a hard paywall (subscription-only).
