### ISSUE TITLE
Request to add this sites:businesstimes & theedgesingapore

### ISSUE THREAD

**Issue by e441e** [magnolia1234-new/bypass-paywalls-chrome-clean#6]
Hi, 

I've tried using the custom sites method stated for these websites but it doesn't work. It seems to require a paid subscription to view the articles. Is there a way to bypass them like those websites you listed?

https://www.theedgesingapore.com/capital/banking-finance/dbs-uob-forecast-cut-dividends-year-ocbc-resorts-script-bear-case-says

https://www.businesstimes.com.sg/opinion/consequences-to-ponder-if-the-us-fed-indulges-in-qe-infinity

**Comment by magnolia1234-new** [comment]
Both sites have a hard paywall (subscription-only).
