### ISSUE TITLE
superguide.com.au

### ISSUE THREAD

**Issue by danielgruber8** [magnolia1234-new/bypass-paywalls-chrome-clean#7]
can the premium articles be unlocked at all?
http://superguidedev.wpengine.com/premium-access-content

Main site
https://www.superguide.com.au/

Actually the "full text" of this premium article was able to be opened in incognito mode....

https://www.superguide.com.au/boost-your-superannuation/crunching-the-numbers-a-1-6-million-retirement

**Comment by magnolia1234-new** [comment]
For now you can add a custom site with Googlebot-fix.
PS lots of Australian financial sites lately.

**Comment by danielgruber8** [comment]
> For now you can add a custom site with Googlebot-fix.

Not on my work laptop ;) I can't upgrade Firefox as don't have admin rights? 
And that old uncaught error doesn't let me click on the custom sites button....

**Comment by magnolia1234-new** [comment]
You opened a Chrome issue though.
Which old Firefox (ESR?) version again?

**Comment by danielgruber8** [comment]
Firefox 64 on Win 10 :)

**Comment by magnolia1234-new** [comment]
I'll add an additional custom-link in the icon/popup-menu in the next release.
Old Firefox (v64) has issues with relative links (in add-on).

**Comment by magnolia1234-new** [comment]
@danielgruber8 Check new FF-release v1.7.0.4.
You can now add superguide.com.au to custom sites (also in FF v64) ;-)
