### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by garlandeau** [magnolia1234-new/bypass-paywalls-chrome-clean#8]
It is working fine but there is an error with the new extension as you can see. I am using Chrome on Windows.

![error](https://user-images.githubusercontent.com/62502727/79988723-a1ffd100-84b7-11ea-83c9-1a396ca20633.png)

**Comment by magnolia1234-new** [comment]
Thumbs.db is not part of the BPC-extension, but local thumbsnail-database (of folder) set by Windows.
Change the view of the folder and delete this file.
