### ISSUE TITLE
Gestion.pe 

### ISSUE THREAD

**Issue by rnzdnyr** [magnolia1234-new/bypass-paywalls-chrome-clean#9]
Sorry to bother but lately I have been experiencing some issues with gestion.pe. I haven't been able to read the following article:
https://gestion.pe/economia/empresas/servicio-de-delivery-llegaria-a-crecer-30-en-proximos-dos-a-tres-meses-noticia/?ref=gesr&fbclid=IwAR2v0P7SHlA2bzOWI-nlCZg0sfSYcvCATRGVga7pGzHQAbeHeru_nJc-YHo#utm_source=facebook&utm_medium=organic&utm_campaign=notas-cerradas-delivery
All I can see is the headline and a photo but no content.
As always, thank you very much.

**Comment by magnolia1234-new** [comment]
Yes, Gestion.pe/ElComercio.pe upgraded their paywall, but it looks like it can be fixed (at least the text).

**Comment by magnolia1234-new** [comment]
Fixed in latest master-zip.
Also new fix for ElComercio.pe.

**Comment by rnzdnyr** [comment]
Thank you very much! :)
